name: Create dist and publish

on:
  push

jobs:
  package_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0
      
      - name: Run PSSemanticRelease
        shell: pwsh
        run: |
          Import-Module ./PSSemanticRelease -Force
          Invoke-SemanticRelease
        env:
          NUGET_PUBLISHER: ${{ vars.NUGET_PUBLISHER }}
          NUGET_PACKAGE_GUID: ${{ vars.NUGET_PACKAGE_GUID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}