name: Create dist and publish

on:
  workflow_dispatch:

jobs:
  package_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false
          fetch-depth: 0
      
      - name: Import Code Signing Certificate
        shell: pwsh
        run: |
          $pfxBase64 = "${{ secrets.CODE_SIGN_PFX }}"
          $pfxBytes = [Convert]::FromBase64String($pfxBase64)
          $pfxPath = "$env:GITHUB_WORKSPACE/temp-cert.pfx"
          [System.IO.File]::WriteAllBytes($pfxPath, $pfxBytes)

          $Password = ConvertTo-SecureString "${{ secrets.CODE_SIGN_PASSWORD }}" -AsPlainText -Force
          $cert = Import-PfxCertificate -FilePath $pfxPath -CertStoreLocation Cert:\CurrentUser\My -Password $Password
          Write-Host "Certificate imported: $($cert.Thumbprint)"
      
      - name: Run PSSemanticRelease
        shell: pwsh
        run: |
          Import-Module ./PSSemanticRelease -Force
          Invoke-SemanticRelease
        env:
          NUGET_PUBLISHER: ${{ vars.NUGET_PUBLISHER }}
          NUGET_PACKAGE_GUID: ${{ vars.NUGET_PACKAGE_GUID }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}